### ISSUE TITLE
Ask for evaluation code

### ISSUE THREAD

**Issue by hongge831** [Tsingularity/dift#12]
Nice work! Would you please provide us with the code of Benchmark Evaluation? Or can you provide anyplace of similar evaluation code
you refer?
especially evaluation of the datasets of  SPair-71k, PF-WILLOW and CUB-200-2011

**Comment by Tsingularity** [comment]
Hi, thanks for your interest in our work!

We are still in the process of organizing evaluation codes and I gonna keep you updated when it's ready. And here're a few things you can refer to for your own implementation:

1. For semantic correspondence evaluations, we modify upon multiple previous works' codebases including [CATs](https://github.com/SunghwanHong/Cost-Aggregation-transformers), [NeuralCongealing](https://github.com/dolev104/neural_congealing). For Spair, we make our own evaluation pipeline for the following reason:  many existing methods are taking both images as input so they need to evaluate on image pairs one-by-one independently. But this is not efficient for our case (especially when Spair has 11k test pairs) because DIFT only needs to query one image's feature once. so we first save all images' features, then doing matching using semantic correspondence.

2. For geometric correspondence, we modify the code from [CAPS](https://github.com/qianqianwang68/caps).

3. For temporal correspondence, we modify the code from [DINO](https://github.com/facebookresearch/dino) (for DAVIS) and [VideoWalk](https://github.com/ajabri/videowalk) (for JHMDB).

Hope this helps!

**Comment by Tsingularity** [comment]
@hongge831 I just pushed a cleaned-up version of our evaluation code. Hope this helps!
