### ISSUE TITLE
Demo error

### ISSUE THREAD

**Issue by 201820894** [Tsingularity/dift#13]
<img width="1112" alt="image" src="https://github.com/Tsingularity/dift/assets/90363698/5d8d96c8-f628-4f9e-b64b-9ea6c71fa604">
Thanks for great work! 

While implementing demo, I experienced the error above.

It worked well when I set do_classifier_free_guidance as True(it was originally set as False)

It seems like negative prompt embedding becomes Nonetype when I set do_classifier_free_guidance False.

If code is wrong, please tell me!

**Comment by Tsingularity** [comment]
Hi, thanks for your interest in our work!

This error is due to the update of diffusers library, where they [change](https://github1s.com/huggingface/diffusers/blob/HEAD/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L233-L235) the output of `_encode_prompt()`: 
```
deprecation_message = "`_encode_prompt()` is deprecated and it will be removed in a future version. Use `encode_prompt()` instead. Also, be aware that the output format changed from a concatenated tensor to a tuple."
``` 
Our code is based on version 0.15.0 as in the installation [environment](https://github.com/Tsingularity/dift/blob/main/environment.yml#L118).

So, there are two solutions:
1. install the specific diffusers version: `pip install diffusers==0.15.0`
2. adapt the code to the new diffusers functions: 
```
        # prompt_embeds = self.pipe._encode_prompt(
        #     prompt=prompt,
        #     device='cuda',
        #     num_images_per_prompt=1,
        #     do_classifier_free_guidance=False) # [1, 77, dim]

        prompt_embeds = self.pipe.encode_prompt(
            prompt=prompt,
            device='cuda',
            num_images_per_prompt=1,
            do_classifier_free_guidance=False)[0] # [1, 77, dim]
``` 
where you comment our the previous function call above and replace with the code below. I just tested in the colab and it should work.

Just let me know if you have any more questions!

**Comment by 201820894** [comment]
It works! Thanks!
