### ISSUE TITLE
Using Application: Edit Propagation

### ISSUE THREAD

**Issue by Limbicnation** [Tsingularity/dift#2]
Hello,
Great work!
I would like to know how I would go about using the "Edit Propagation" method as seen in the last example.
Thank you very much!

**Comment by Tsingularity** [comment]
Hi, thanks for your interest in our work!

More implementaiton details could be found in section 5.3 of our [paper](https://arxiv.org/pdf/2306.03881.pdf). Basically speaking, for the input image with the added sticker, we firstly densely sample a set of source points around the sticker region (for example, for the cat face example in figure 6, we sample point around the eyes and the mouth of the source image). Then for a given target image that we want to propogate the edits to, we use DIFT to find their corresponding target points. Based on these matched (source point, target point) pairs, we can use `cv2.findHomography()` to calculate a homography transformation from source image to target image. Then we simply apply this transformation to the sticker, to propagate it to the target image.

Hope this helps!

**Comment by Limbicnation** [comment]
Hi,

Thank you for your reply! I appreciate your explanation regarding the implementation details. Section 5.3 of your paper seems to contain more in-depth information, which I will certainly explore.

However, I must admit that I am not very familiar with Python, so I was wondering if there is a practical example or code snippet you could provide on GitHub that demonstrates the implementation of this feature. It would greatly assist me in understanding and implementing it effectively.

Thank you for your assistance!

Best regards,
Gero

**Comment by Tsingularity** [comment]
Hi Gero, thanks for the suggestion! I don't think there're existing examples online that implement what we are doing here exactly. But you should be able to reproduce the results following the instruction above. We'll also let you know when we release this part of code.

Thanks!

**Comment by hukz18** [comment]
Hi Tsinghularity,

Thank you for your explanation of the procedure of edit propagation, If I understood it properly, you perform a lot of correspondence matching between the edited source image and the unedited target image, and map the edition to the correspondent points, right?

I tried to verify whether these points could be mapped to the correct place, and while some of them are mapped to the right area, some can't find a correct place, like the white pompon of the doggy:

![image-20231017113037936](https://github.com/Tsingularity/dift/assets/49591637/208ef0bd-0c43-46af-ba5d-7ed413a80869)
![image-20231017113148160](https://github.com/Tsingularity/dift/assets/49591637/2a93eb30-4029-4bdf-8143-517dd2b73029)
![image-20231017113211457](https://github.com/Tsingularity/dift/assets/49591637/c845bab7-1618-40e9-8986-53de3575c675)

I reckon it's very hard to map the edition directly to the unedited target image because there are not any relevant objects. Could you kindly explain how this problem is solved, or do I misunderstand the procedure here? Thanks!

**Comment by Tsingularity** [comment]
Hi @hukz18 , thanks for your interest in our work!

Sorry for the confusion here, but `perform a lot of correspondence matching between the edited source image and the unedited target image` is not what we did. The correspondence matching is actually happening between the `original unedited` source image and the `unedited` target image. For the example shown above, it would be two dog images without the hats.

More specifically, on the source image, we will sample the points covered by the edited region (for example, the hat), and use DIFT to find the corresponding points on the target image, then use the matches to calculate a homography transformation, and finally apply it to the hat.

Feel free to let me know if you have more questions!

**Comment by Tsingularity** [comment]
@Limbicnation @hukz18 I just pushed a cleaned-up version of our implementation on edit propagation [here](https://github.com/Tsingularity/dift/blob/main/edit_propagation.ipynb). Hope this helps!

**Comment by Limbicnation** [comment]
> @Limbicnation @hukz18 I just pushed a cleaned-up version of our implementation on edit propagation [here](https://github.com/Tsingularity/dift/blob/main/edit_propagation.ipynb). Hope this helps!

@Tsingularity Thank you very much!

**Comment by hukz18** [comment]
> @Limbicnation @hukz18 I just pushed a cleaned-up version of our implementation on edit propagation [here](https://github.com/Tsingularity/dift/blob/main/edit_propagation.ipynb). Hope this helps!

Thank you, guys, this really helps!
