### ISSUE TITLE
Question regarding edit propagation

### ISSUE THREAD

**Issue by crazymi** [Tsingularity/dift#8]
Hello,
Thanks for great work! DIFT is truly impressive and I believe it offers endless possibilities for downstream tasks.

I have a question about the Edit Propagation discussed in your paper. From my understanding, one would initially paste a sticker onto the source image, then extract a matching mask in the target image using DIFT, and subsequently apply the transformation from source mask to target mask. Am I understanding this correctly?

If so, I have a question about how the system handles features that are present in the source image but missing in the target image through DIFT. For instance, in the project page, there's an example of a dog wearing a Santa hat. Given that the target image doesn't have the hat, it would seem challenging to extract the corresponding feature map from the target. Could you kindly explain it please?

Thank you so much!

**Comment by Tsingularity** [comment]
Hi, thanks for your interest in our work!

`one would initially paste a sticker onto the source image, then extract a matching mask in the target image using DIFT, and subsequently apply the transformation from source mask to target mask.`
Your understanding is correct! The sticker is manually added by the user, and we densely sample points inside the sticker area on the **original source image**, and use them to find corresponding points on the target image. Then we use the matches to do homography estimation.

`there's an example of a dog wearing a Santa hat. Given that the target image doesn't have the hat, it would seem challenging to extract the corresponding feature map from the target.`
Sorry for the confusion here. Like what is mentioned above, the features are extracted from the original source dog image **without** the hat sticker, so the matches is actually being done using the features on the head instead of hat.

Feel free to ask more question!

**Comment by crazymi** [comment]
Hi, thanks for your reply!

Your explanation was super helpful and cleared up all my questions about edit propagation. Really appreciate it! 😊

Thanks again!
